### ISSUE TITLE
Pan-to-pop gesture not responsive

### ISSUE THREAD

**Issue by mixerzeyu** [Enricoza/EZCustomNavigation#12]
Firstly love simplicity of the plugin!

Upon some testing I realized the pan-to-pop gesture isn't quite responsive compared to similar gestures implemented in major apps like Facebook.

For example, if you make a quick swipe that only moves the screen a little to the right, the view will bounce back instead of getting dismissed. The bounce-back requires the user to swipe again with a larger finger movement, thus slows down user action and makes the interaction feel not responsive.

It would be ideal if this can be fixed, otherwise the custom pan-to-pop gesture isn't quite usable.

Thanks.

**Comment by Enricoza** [comment]
Hi @mixerzeyu, thanks for the suggestion! 
It should be a really easy improvement to make, but will need to do some testing in order to make it exactly like facebook (or actually as the basic UIViewController which is my target implementation).

If you wanna play around it yourself, the edit should be made in the `EZNavigationControllerTransitionHelper+HandlePanGesture.swift` file, taking in consideration the speed of the gesture when determining if the animation should be completed or cancelled.

I think I'll be able to fix this by the end of the week. I'll keep you posted.

**Comment by Enricoza** [comment]
Hi again @mixerzeyu,
version `1.2.0` has just been released and it should solve your issue. 
Now the gesture and the animation should feel much more responsive and smooth.

I'm closing this for now but, please, feel free to reopen this or any other issue if you feel something else could be improved!

**Comment by mixerzeyu** [comment]
Thank a lot @Enricoza - it works great now!!
